# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='entry_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date added'),
        ),
    ]
